### PR TITLE
Add to list

### LINKED ISSUE #36: add item(s) to list
- click item to add it to a list of choice

### PR DESCRIPTION
**Pull request by finny19**
- Dropdown selection of lists added to the detail section that comes up when you press the + button next to a plant
- Add button is next to this dropdown and will add the selected plant to the selected list
- Add button will redirect users to the list that will now have the plant in it listed with the date (date when added), KewID, ListID, and a blank location

- The Edit/Details/Delete buttons in the list do not currently do anything and will need functionality in the future

Known bugs:
- Trying to add a duplicate of a plant to a list will crash the site
- Trying to add a plant to the "Select List" part of the dropdown will crash the site

Closes #36

### CODE REVIEW

**Comment by k-atej** [comment]
Looks good! Just a few more things, that could be addressed separately. 
- list pages display all plants associated with any list, as opposed to the plants associated with that specific list
- should display similar info to search details page (plant taxon instead of IDs)

**Review by k-atej — CHANGES_REQUESTED** [review]
I think the ISG files can be removed from this pull request!

**Comment by finny19** [comment]
> I think the ISG files can be removed from this pull request!

Recent commits fix these problems:
- ISG files that were added in this push have been removed
- Lists only display plants that are associated with that specific list
- Plants display with their scientific name (Genus and specific epithet)
- Lists no longer have a list column
- Lists now are displayed with their names on top rather than "Index"
- Edit/Detail/Delete buttons now work (Edit allows to change the date but not the locations because the database currently does not have locations, detail will redirect to the "Detail" page of the specific plant, Delete will take users to an "are you sure" page where you can confirm deleting the plant)
- The confirm buttons on both the edit and delete pages will take users back to the list after making the changes
- The "Back to List" buttons on the edit/details/delete buttons will take users back to the list
- There are now proper error messages when adding a duplicate to a list or adding something to no list at all

This branch will now also...
Closes #44 
Closes #43

**Comment by k-atej** [comment]
There's something funky going on with the database, but I was able to fix that by merging main into your branch. I think we should try to get that fixed before merging, just in case. 

Otherwise, looks good! Just a few things, which could be separate issues.
- Clicking "items" button on list without any items causes crash
- Clicking "back to list" from the details page of a list item does not return to the list

**Comment by finny19** [comment]
Right, I forgot about the Details thing. That's because Details goes into the Taxa folder to show details so it would be much harder for it to remember where it came from. 
I wonder what's going on with the items thing... I can take one last look in a bit.

As for the funky database shenanigans... This is a thing that I had to mess around with quite a bit. In the .gitignore file, just putting in ISG.db-* broke the entire plant database... Which is why the .gitignore file specifically lists ISG.db-shm and ISG.db-wal but I guess it didn't work entirely right? I'm not sure though.

**Review by k-atej — APPROVED** [review]

**Comment by k-atej** [comment]
Database worked for me! Items link still crashes, but that and the details back-to-list functionality can be a later issue.

**Pull request merged**
